### ISSUE TITLE
What is addMinGeneField function in runThresholdsINIT.m?

### ISSUE THREAD

**Issue by sangmi9618** [LewisLabUCSD/Context_Specific_Models_from_GeMS#1]
Hello.
I am Sang Mi Lee from KAIST, South Korea.
I have been looking for your code after reading your papers.
But I wonder what is addMinGeneField function in `eval([tName,'= addMinGeneField(cMod, gene_exp, gene_names, th, 1);']);` 147th line of Extraction Methods/runThresholdsINIT.m.
I could not find addMinGeneField.m in your repository.

Thanks.
Sang Mi

**Comment by arichelle** [comment]
Hi Sang Mi,

sorry about that. I just uploaded the file in 
Context_Specific_Models_from_GeMS/Extraction Methods/additional_scripts/addMinGeneField.m 


Note that the code in this repository is compatible with the COBRA 2.0 release circa 2015, and may not be compatible with COBRA 3.0 due to major changes in the COBRA toolbox. We suggest researchers developing context specific models to use the new version of the function createTissueSpecificModel.m available with COBRA 3.0 in order to ensure the usage of the most up-to-date extraction features

Best
